### ISSUE TITLE
Option to attach class name to input

### ISSUE THREAD

**Issue by simonh1000** [etaque/elm-form#10]
In order to use bootstrap I need to attach a class name to the input fields, but I don;t think i can see a way to do that?

**Comment by etaque** [comment]
Hello,
Last parameter of inputs is a list of attributes for the html input:
https://github.com/etaque/elm-simple-form/blob/master/example/src/View/Bootstrap.elm#L47

**Comment by simonh1000** [comment]
My apologies, I was working via your helper functions, rather than the raw components. I will write my own helpers so I expose the things that I need.
