### ISSUE TITLE
Support for Ints?

### ISSUE THREAD

**Issue by sid-kap** [etaque/elm-form#103]
I see that you've implemented `getFieldAsString` and `getFieldAsBool`. Do you plan on doing something similar for other types, like int/double?

**Comment by etaque** [comment]
Which additional types would you need? Note that there is nothing like double in Elm.

**Comment by sid-kap** [comment]
I decided to not use Elm, so maybe this is moot now. But I would think that support for Elm's number type would make sense, if you've supported bools...
