### ISSUE TITLE
Email validator too permissive?

### ISSUE THREAD

**Issue by ngw** [etaque/elm-form#107]
Hello, I have this validator:

    (field "user[email]" (email |> andThen nonEmpty))

and this string "ngw@nofeed" validates, while for example "ngw" doesn't.
Am I doing something wrong? email should validate the format.

If that is the case I guess the regexp is far too permissive

**Comment by etaque** [comment]
Hi,
Emails are quite permissive by nature, foo@bar is a valid email for instance, see examples here:
https://en.wikipedia.org/wiki/Email_address#Examples

Also some earlier discussions on validation regexp:
https://github.com/etaque/elm-form/issues/96

If you need a more restrictive validation, you can create a custom one. But it might not be necessary: if you really need to validate the email, best is to send a confirmation url.

**Comment by ngw** [comment]
Very surprised that address is valid. Ok, thanks a lot.
