### ISSUE TITLE
Why is "elm-test" a dependency?

### ISSUE THREAD

**Issue by martinmaillard** [etaque/elm-form#109]
Hi,

Is "elm-test" required to use this package? I don't use it in my project and it causes a compilation issue that I don't really want to solve if I don't have to.

**Comment by dillonkearns** [comment]
Hi @martinmaillard, the reason that `elm-test` is a dependency is so that users can unit test their validations, see pull request #91.

If you run `elm-package install -y elm-community/elm-test` then that should fix your compilation issue I believe.

**Comment by martinmaillard** [comment]
Ok, I see. That makes sense, thanks :)

My compilation error was actually unrelated to elm-form (other than the fact that it was caused by elm-test).
