### ISSUE TITLE
Use 'onChange' rather than 'onBlur' for select elements to trigger validation

### ISSUE THREAD

**Issue by simonh1000** [etaque/elm-form#11]
Per https://groups.google.com/forum/#!topic/elm-discuss/p3U2gslBUiI

**Comment by ThomasWeiser** [comment]
Yes, would also strongly prefer a immediate feedback.

@etaque I think you agreed already on the elm-discuss, but allow me to corroborate the argument.

Simple use case: A sign-in form with fields for username, password and a button.
Both input fields needs to be filled in. The button shall be disabled as long as the form doesn't validate.

Now assume the user has filled in the fields. For now she still has to blur the last field for the button to become enabled. She cannot simply click on the button.

**Comment by etaque** [comment]
I do agree. Although we need to find a solution that doesn't show error message on each keypress ; for that we can decorrelate validation and error printing so submit button is clickable, or throttle validation (but that would imply changing the `update` signature I believe).

Would gladly accept a PR, I'm short in time for my packages these days :)

**Comment by ThomasWeiser** [comment]
Thank you, etaque!

Maybe I can dig into the issue after my short term project is finished (presumably next week).
But I cannot make a promise.

**Comment by etaque** [comment]
I have a working implementation in this branch:
https://github.com/etaque/elm-simple-form/tree/specialized-fields

Example looks good but I haven't tested it more seriously, I should be able to publish it tomorrow if it's good for you.

**Comment by simonh1000** [comment]
At first glance, looks to work. I see you are now exposing the Actions explicitly and have retired the functions that create them. This is going to allow me to drop one of my ports :-)

**Comment by etaque** [comment]
I think it's good. Closing, I'll release 2.0.0 tomorrow.

**Comment by etaque** [comment]
@simonh1000 @ThomasWeiser 2.0.0 is out!

**Comment by simonh1000** [comment]
Fab - thanks
