### ISSUE TITLE
Generic select for foreign keys

### ISSUE THREAD

**Issue by emanuelkoczwara** [etaque/elm-form#13]
Hello,

I'm wondering how to make an input for foreign keys. Value stored in field should be integer, name displayed to the user should be string, I need support for autocompletion (dropdown with data from the server, so http query will be involved), there should be additional 2 buttons, one to add new item (if I want to select something that doesn't exist yet) and one to open a dialog where I can select an item (a list/table with sorting and filtering), is it possible to make such generic 'widget' with pre-wired actions?

**Comment by etaque** [comment]
Hello,
I think it's a nice thing to do but probably outscoping this package. You could build a dedicated package on top on this one?

**Comment by emanuelkoczwara** [comment]
Hello,

Ok.
