### ISSUE TITLE
Not allowing Empty fields

### ISSUE THREAD

**Issue by simonh1000** [etaque/elm-form#14]
I have the following

```
validation =
    form3 MyForm
        (get "Name" string `andThen` nonEmpty)
        (get "Version" string)
        (get "Product" string `andThen` nonEmpty)

initFields =
    [ ("Name", Field.Text "")
    , ("Version", Field.Text "")
    , ("Product", Field.Text "")
    ]
init =
    ( Model
        (Form.initial initFields validation)
....
```

and yet the form is not validating when field `versionName` is empty. Am I missing something?

**Comment by etaque** [comment]
What does `Form.Input.dumpErrors` render for this?

**Comment by simonh1000** [comment]
dumpErrors provides `Version: Empty`.

When I first opened this issue I had `initFields = []`, and then I got `Version: InvalidString`

Full code at https://github.com/simonh1000/elm-mdbootstrap/blob/master/src/MyForm.elm

**Comment by simonh1000** [comment]
OK I found what was happening in the code, and have submitted a patch

**Comment by simonh1000** [comment]
OK, so I have now found the `emptyString` validator (sorry for not noticing that before). I've also withdrawn my PR as it seemed to break things. 

But I am left with a question about the `string` validator

```
string : Validation e String
string v =
  case Field.asString v of
    Just s ->
      if String.isEmpty s then
        Err Empty
      else
        Ok s

    Nothing ->
      Err InvalidString
```

It feels to me that this should accept any string, including the empty string (obviating the need for `emptyString`), and it `noneEmpty` that should complain about empty strings if called. As things stand `nonEmpty` appears to be redundant, at least for strings.
