### ISSUE TITLE
Add chain example?

### ISSUE THREAD

**Issue by pablohirafuji** [etaque/elm-form#15]
Hi,

Thanks for the library, it's really neat! I've studied the example's source code, and the action `SubmitUser` is never used. I'm trying to implement it but no success so far. Could you make an example or explain how can I chain `Form.submit` with a custom action?

Thank you!

**Comment by emanuelkoczwara** [comment]
Hello,

Instead of passing `formAction` directly to `Form.update`:

```
FormAction formAction ->
    ({ model | form = Form.update formAction form}, Effects.none)
```

you can try something like:

```
FormAction formAction ->
    let
        newForm = Form.update formAction form
        formResult = Form.getOutput newForm
    in
        if formAction == Form.submit then
          case formResult of           
              Just x -> -- form validated and we have our data
              Nothing -> -- form didn't pass validation
        else   
          -- there was reset or something else...
```

Note that you can't pattern match on `Form.Submit`, you need to use if/then/else and check `formAction` against `Form.submit`.

**Comment by pablohirafuji** [comment]
Solution worked! Thank you!

**Comment by pablohirafuji** [comment]
Should I make a pull request to add this pattern to the example?

**Comment by etaque** [comment]
Hi,
In fact the best place to trigger the custom action (`SubmitUser`) is from the view, where you can pattern match on `Form.getOutput` and choose if you want to `Form.submit` or send your custom action. Yes, that would be a good addition to the example and docs!

**Comment by emanuelkoczwara** [comment]
Hello,

Could you expose Action value constructors? I think it would be logically more correct to handle this explicitly in update.

**Comment by etaque** [comment]
Well, it's a valid point of view. In the context of #11 I'll probably reorganize action constructors for next version, I'll expose them too.

**Comment by etaque** [comment]
Next version will expose constructors, closing.

**Comment by etaque** [comment]
@pablohirafuji @emanuelkoczwara v2.0.0 is out with exposed actions.
