### ISSUE TITLE
example index.html?

### ISSUE THREAD

**Issue by larryhengl** [etaque/elm-form#17]
Hi, thanks for sharing this elm package!  I'm eager to try it as I learn elm.

I pulled down the example and ran the make call, `$ elm make src/Main.elm --output main.js` per the README, but it doesn't create the index.html file as suggested.  Did I miss a step (elm newbie here)?  

I then tried `$ elm make src/Main.elm --output index.html` and that does generate the form, but without any of the styling.  

I do see there is a .gitignore entry for index.html, perhaps that was intentional?

ideas?

**Comment by etaque** [comment]
Ah yes, I messed up when I created the `gh-pages` branch, the file is here:
https://github.com/etaque/elm-simple-form/blob/gh-pages/example/index.html

**Comment by larryhengl** [comment]
great.  i'll go ahead and close this then.  thanks!
