### ISSUE TITLE
Iterate over fields to render form

### ISSUE THREAD

**Issue by emanuelkoczwara** [etaque/elm-form#18]
Hello, 

Is it possible to iterate over fields to render form? There should be some way to inject field names and optional parameters for rendering like placeholder or help text. With this info I would like to iterate over that, pattern match on some value constructors and render form inputs using pre-wired primitives from Form.Input.

**Comment by etaque** [comment]
Form only knows about initialized fields or changed values, so it's probably not the "reference" you need for your iteration, but you probably have a list of the field names, somewhere outside? Then you can call a `getFieldAsString/Bool` on each?

**Comment by emanuelkoczwara** [comment]
Hello, 

Ok, this sounds good, thanks.

**Comment by simonh1000** [comment]
Yes, I do that in my forms with no problem.
Look at https://github.com/etaque/elm-simple-form/issues/12 to see how to validate a list

**Comment by etaque** [comment]
I guess @emanuelkoczwara already knows about #12 ;-)
