### ISSUE TITLE
How do you preventDefault (as in prevent form submission)

### ISSUE THREAD

**Issue by chalmagean** [etaque/elm-form#30]
When there are validation errors present, I would like to stop the form from submitting and only submit the form if no validation errors are present. What's the best way to achieve that behavior with elm-simple-form?

Thanks

**Comment by pablohirafuji** [comment]
Hey,
If I understood corretly, you should use the onSubmit attribute in the [Html.Events package](http://package.elm-lang.org/packages/elm-lang/html/1.0.0/Html-Events#onSubmit), like:

``` elm
view : ViewModel -> Html Msg
view model =
    Html.form
        [ Html.Events.onSubmit (onSubmitMsg model.form) ]
        [ ... -- Your form view
        , Html.button [ type' "submit" ] [ text "Send" ]
        ]

onSubmitMsg form =
    case Form.getOutput form of
        Nothing -> FormMsg Form.Submit
        Just validForm -> Submit validForm
```

This works because the onSubmit event already comes with `preventDefault = True`. If you need different behavior, use [onWithOptions](http://package.elm-lang.org/packages/elm-lang/html/1.0.0/Html-Events#onWithOptions) to create a customized version of onSubmit.

**Comment by etaque** [comment]
Hello,
Do you want to prevent the browser submit event or something else?
Could you provide some code to show what you're trying to do?

**Comment by chalmagean** [comment]
I haven't got chance to try what @pablohirafuji said but yes, what I want is to prevent the browser submitting the form if validations are not passing.

**Comment by etaque** [comment]
Okey, so alternatively you can also use a basic `button` for submit, or avoid using the `form` tag.

**Comment by chalmagean** [comment]
Not using the `form` tag means I loose a few things like auto submit on enter (and not sure if it's valid HTML).

Here's the code: https://gist.github.com/chalmagean/f06eea7cf00c156456f463621958d848

The problems is that `Html.form` expects `List (Html Msg)` and I'm giving it `List (Html Form.Msg)`. So I'm  still not sure how to fix this.

**Comment by pablohirafuji** [comment]
Hey,
On submit you are double mapping to FormMsg (in line 70 as `Html.map FormMsg` and line 113 `FormMsg Form.Submit`). Don't map the attributes, just the formView, and you will have to handle the Submit case. Here's an example: https://gist.github.com/pablohirafuji/46c452341853f8693dee5fa90c877731.

**Comment by chalmagean** [comment]
@pablohirafuji sweet! That seems to work. Thank you.
