### ISSUE TITLE
Bug: `andThen` should return GroupErrors (partially solved)

### ISSUE THREAD

**Issue by simonh1000** [etaque/elm-form#36]
Please see https://gist.github.com/simonh1000/67c1c98c8c7c7a63019bd4a7a9f85ec7 

I am building a conditional validator that - in one instance - checks that a number is divisible by 4.

```
valCount : Validation CustomError Float
valCount =
    V.get "Select" V.string
    `V.andThen` (\binding ->
        case binding of
            "option2" ->
                V.get "Count" V.float
                `V.andThen` (\tpc ->
                    case round tpc `rem` 4 == 0 of
                        True ->
                            valFloat "Count"    -- checks > 0
                        _ ->
                            let _ = Debug.log "failing" tpc
                            in
                            V.fail InvalidFloat)
            _ ->
                valFloat "Count")
```

The problem is that when the divisibility check fails, the function returns `InvalidFloat` whereas it needs to return `GroupErrors <| Dict.fromList [(field, InvalidFloat)]` if the errors are to be returned to the user. In practise the developer is faced with the tricky combination of `getOutput == Nothing` but `errors == Dict.empty`!

So, I can make this work with 
`V.fail (GroupErrors <| Dict.fromList [("Count", InvalidFloat)]))` 
but I have a feeling that `andThen` needs tweaking, or the docs need updating to explain what is happening.

== Update ==
It is sufficient to pass a negative number to 

```
V.get "Count" V.float `V.andThen` (V.minFloat 0)
```

to get `getOutput == Nothing` but `errors == Dict.empty`

**Comment by simonh1000** [comment]
**Update**
I have now found that I can rewrite my validator as 

```
valCount : Validation CustomError Float
valCount =
    V.get "Select" V.string
    `V.andThen` (\binding ->
        case binding of
            "option2" ->
                V.get "Count" valDiv4
            _ ->
                valFloat "Count")

valDiv4 =
    V.float `V.andThen`
        (\flt ->
            case (round flt `rem` 4 == 0) && flt > 0 of
                True ->
                    V.succeed flt
                _ ->
                    V.fail InvalidFloat)
```

or

```
V.get "Count" (V.float `V.andThen` V.minFloat 0)
```

The 'trick' is to apply `get` to the rest of the validation in one go, as `get` returns the `GroupErrors` that are needed

**Comment by etaque** [comment]
Hi Simon, 
could you reopen an issue with the remaining bug, and a way to reproduce it? (the "SCSSE" thing... I don't remember the letters sorry).
Thanks
