### ISSUE TITLE
Support: Validate dynamic list of fields

### ISSUE THREAD

**Issue by DavidHernandez** [etaque/elm-form#50]
We are building a rather complex form. We have a couple of fields that we will duplicate depending on something set somewhere else. For example, we have a text field to select a number of people and then, we add a "name" and "last name" field for each person.

I have something like this:

```
type alias Model =
  { form : Form () Items }

type alias Items =
  { field : String
  , secondField : String
  -- Other fields
  , people : List Person
  }

type alias Person =
  { name : String
  , lastName : String
  }
```

But is in the validation when I'm running out of ideas. I don't know how to handle the List part on my validation. I guess I need to create a custom validation function, but following the current example I was not able to find a way to do it: https://github.com/etaque/elm-simple-form/blob/master/example/src/Model.elm#L90

My current validation looks like this:

```
(|:) =
  Validate.apply

validate : Validation CustomError Items
validate =
  Validate.succeed Items
    |: (get "field" string)
    |: (get "secondField" string)
    |: (get "people" validatePeople)

validatePeople : Validation CustomError List Person
validatePeople =
```

And here is where I'm stuck. Can you point me in the right direction? If I'm able to resolve this, I will provide an example with the code to show how it works and I will write a post explaining it.

**Comment by amitaibu** [comment]
Here's an example of such a form we need:

![test_item_tobi___backoffice](https://cloud.githubusercontent.com/assets/125707/19551632/d5d5e554-96b4-11e6-85f4-24ee9c9c13ab.jpg)

**Comment by etaque** [comment]
Hi,
That's not possible in the current state of the package. We need to add a `list` operator and a way to address a list element in field path (something like `foo.bar[3]`). An interesting feature to have for sure :)
I might have time to look at it in a few days but no guarantee. In the meantime you could explore having multiple forms?

**Comment by amitaibu** [comment]
> In the meantime you could explore having multiple forms?

Yeah, I'm trying to look at multiple forms, although it means that the validations will be scattered around, so it can be just an intermediate solution.

btw, the package rocks! :)

**Comment by amitaibu** [comment]
> Yeah, I'm trying to look at multiple forms

hmm, for my use case multiple forms are not enough, as in fact the multiple fields are wrapped with another form. I'll open another issue to explain where I'm stuck.

**Comment by etaque** [comment]
Progress is happening here:
https://github.com/etaque/elm-simple-form/commits/dynamic-fields-list

**Comment by etaque** [comment]
Done, about to publish.
