### ISSUE TITLE
Example has unused Field

### ISSUE THREAD

**Issue by amitaibu** [etaque/elm-form#52]
I'm not sure if it is a mistake or not, but [this](https://github.com/etaque/elm-simple-form/blob/02424085fd39d7c8fe46f51ad0cc0b3ffda35805/example/src/Model.elm#L53) doesn't seem to be used.

**Comment by etaque** [comment]
yes, definitely looks like a mistake!

**Comment by amitaibu** [comment]
I'll create a PR

**Comment by amitaibu** [comment]
Closed in favor of #59
