### ISSUE TITLE
Use of defaultValue instead of value

### ISSUE THREAD

**Issue by stil4m** [etaque/elm-form#54]
A known issue with using value is that when you have you type really fast some update are overwritten with the next one, which results in incomplete text. The fix for this is to use `defaultValue`. Is there a reason why this library uses `value`?

We currently have problems testing this with end-to-end tests and `defaultValue` will probably fix this.

**Comment by pablohirafuji** [comment]
Using `defaultValue`, if the user edit the textarea once, any further update from javascript is not reflected.

More [here](https://github.com/etaque/elm-simple-form/pull/39) and [here](https://github.com/etaque/elm-simple-form/pull/31).

I still haven't found a solution for both issues.

**Comment by etaque** [comment]
@pablohirafuji when you say "update from javascript", do you include elm-generated js?
If it's just when trying to control an elm-originated textarea from js land, that's probably not the most common usage so it might be a sensible choice to use `defaultValue`.

**Comment by pablohirafuji** [comment]
Consider [this example](https://gist.github.com/pablohirafuji/1fcfec3418c0c17bff0b2fb776d92fe2) (you can run it on http://elm-lang.org/try).

Using `defaultValue`, I can no longer reset the textarea visual value and it can be out of sync with the model value.

Using `value`, we have the "type really fast some update are overwritten" bug, but the visual value is always in sync with the model value.

So we have to choose which one is preferable. I think the `value` one has less critical downside.

If anyone know a solution that does not have neither downsides, please share.

**Comment by stil4m** [comment]
I see the problem you are stating with 'reset the textarea', but in many cases you will submit a form and the form will go away, you will not have to deal with resetting the form fields. In this case there is no 'problem' with using `defaultValue`, but can be with `value`. When I use Elm in production I would favour to use `defaultValue` instead of `value` in this case. In other cases, like resetting a form, I would favour `value`.

Would it be an possibility to use one of the two attributes by default in this package, but being able to pick the other if you explicitly state it? This gives may satisfy everybody their needs.

**Comment by pablohirafuji** [comment]
Yes, you're absolutely right. I was thinking in someone new using the package. It's a frustrating experience not to be able to control the input visual value (happened to me :)).

Using `defaultValue` does not enforce anything like `value` does. So the user still can set the `value` attribute if changing the visual input value is desired, like:

```
Input.textArea state [ value model.state ]
```

I like this solution. Made a [pull request](https://github.com/etaque/elm-simple-form/pull/56) with the change. Maybe add this to the docs help the new users.

**Comment by pablohirafuji** [comment]
@stil4m Thanks for pointing it!

@etaque Let me know if it makes sense. I can update the example (it makes use of Reset) and add this to the docs.

**Comment by etaque** [comment]
Sounds right! PR merged, thanks. Yes, an update on example and docs would be valuable :)

**Comment by pablohirafuji** [comment]
[Done](https://github.com/etaque/elm-simple-form/pull/57) and [done](https://github.com/etaque/elm-simple-form/pull/58) :)

**Comment by stil4m** [comment]
@etaque Can I close this issue since it is fixed? Can you make sure a new packages is uploaded?

**Comment by etaque** [comment]
thanks @pablohirafuji ! closing this, and a new package is coming.

**Comment by etaque** [comment]
5.0.1 is out

**Comment by pablohirafuji** [comment]
@etaque Thank **you** for this package!
