### ISSUE TITLE
How to add other fields types to the form

### ISSUE THREAD

**Issue by amitaibu** [etaque/elm-form#55]
I'm struggling a bit to wire things in, and wonder if someone might already have experience.

I'm trying to see if it's possible to get https://github.com/Bogdanp/elm-datepicker/ or https://github.com/thebritican/elm-autocomplete to play nicely with the form.

Apart of wiring everything together, one of the problems I saw, is how to embed in the middle of the form another element that returns `Html Msg`, since the form is expected to return `Html Form.Msg`

**Comment by amitaibu** [comment]
I was able to make [this](https://github.com/amitaibu/elm-dynamic-fields/tree/78058c5edfa562491e35f0326ef4990efffb6227) compile, however I get a runtime error from elm-datepicker 

![elm](https://cloud.githubusercontent.com/assets/125707/19575717/b8fa1342-9718-11e6-8129-a8292716ab49.jpg)

[Here](https://github.com/amitaibu/elm-dynamic-fields/blob/78058c5edfa562491e35f0326ef4990efffb6227/src/elm/Pages/Form/View.elm#L16-L19) is where I have the date-picker above the rest of the form. However I wonder if it's possible to somehow get that field in the middle of the form.

/cc @Bogdanp

**Comment by etaque** [comment]
tricky... no easy answer on this, but you could explore having a `type FormMsg = BasicField Form.Msg | DatePickerField DatePicker.Msg` so you can mix them in the view.

**Comment by amitaibu** [comment]
It was actually a little easier than I thought, to get a basic field (just a simple input, nothing fancy) in the middle of the form.

Something like [this](https://github.com/amitaibu/elm-dynamic-fields/pull/2/commits/efeaa633b49a25b5d1cb35ae10ff53883488f5d6)

![elm](https://cloud.githubusercontent.com/assets/125707/19736589/a1056602-9bb8-11e6-8c29-a7784a83ff17.jpg)

So it's possible. Now an interesting question is to see if we can have some bridge code, that will allow us to use other field related packages and wire them into simple form. I'll probably need your brain power here @etaque ;)

**Comment by amitaibu** [comment]
Closing this one, as the general support question was answered.
