### ISSUE TITLE
0.18 upgrade

### ISSUE THREAD

**Issue by etaque** [etaque/elm-form#63]
- [x] finish sub lists #60 
- [x] study and maybe reflect changes from `Json.Decode` core API
- [x] do the 0.18 syntax upgrade
- [x] refresh README
- [x] prepare renaming to elm-form #61

**Comment by stephenreddek** [comment]
Would it be possible to publish a version with minimal changes to support 0.18 right away before finishing the rest of these tasks? I'm interested in moving a code-base to 0.18 soon. If that's feasible to do from the main code base, I could help with a PR after running elm-upgrade.

**Comment by etaque** [comment]
Yes it would allow easier and faster upgrade to 0.18. But I'm moving a lot of code in #60 and it's almost finished (just need a better css on the demo), and merge might be hairy if master is migrated to 0.18. 
I'm working on it this evening. Will do a simple upgrade if I don't progress fast enough, I don't want to block people on 0.18 route.

**Comment by etaque** [comment]
Done! and published as 1.0.0 of etaque/elm-simple-form.

Release note: https://github.com/etaque/elm-form/releases/tag/1.0.0

**Comment by amitaibu** [comment]
Thank you!
