### ISSUE TITLE
How do you populate form with dynamic values from network for edit?

### ISSUE THREAD

**Issue by alexofob** [etaque/elm-form#67]
Hi there,

I am creating a form for editing user profile information. User profile info is pulled from the network and then I would populate the values returned from the network in the form so user can update fields where necessary.

What is the easiest way to do this? Setting the initialFields in the init function does not work as the values to be populated is not static but will depend on the information returned from the network.

Thanks.

**Comment by pablohirafuji** [comment]
Hey! You can use the `Form.inital` function. There's an [example](https://github.com/etaque/elm-form#initial-values-and-reset) in the docs.

The process is:
* Receive and decode the json from the network
* With the record, fill the fields following the type `List ( String, Field )` (like the example in the docs)
* Update your model like `{ model | myForm = Form.initial filledFields validation }`

Make sure to set the `value` attribute with `Maybe.withDefault "" state.value`, as seen [here](https://github.com/etaque/elm-form/pull/57/files#diff-bfb877e82b2c89b329fcda943a258611R50), in your views inputs/textareas.

**Comment by etaque** [comment]
as @pablohirafuji said :)

**Comment by alexofob** [comment]
Many thanks for the feedback. I had wanted to implement and share feedback, but now, I decided to go with polymer web components and I had not since had a need to implement the suggestions.
