### ISSUE TITLE
Async validation

### ISSUE THREAD

**Issue by chalmagean** [etaque/elm-form#74]
It would be really awesome to have async validation built in. I can't think of a reason not to have this since most apps need some kind of API validation.

**Comment by etaque** [comment]
This is going to be facilitated by next version, as validation will now be an `update` parameter, so it can be a function of current form state: this is opening the door for conditional validation.

It can also be done outside of form scope for simple cases, when it's just a matter of checking email or id availability.

What's your typical use case?

**Comment by chalmagean** [comment]
I usually need to check against some API/db constraints say for example that an email is unique.

**Comment by etaque** [comment]
Here is an example of merging form errors with server errors:
https://github.com/etaque/tacks/tree/master/client/src/Page/Register

Though form submit is required to show server errors, live and async validation remains an open problem.
