### ISSUE TITLE
Publish a New Version?

### ISSUE THREAD

**Issue by sabine** [etaque/elm-form#79]
Hey, I can see that the validations have been moved out of the model, which is great.

I'm still using 1.0.0 from the package repository and am wondering whether it makes sense to wait for a new version to be published or whether I should rather be including the repo in my `elm-package.json`.

**Comment by etaque** [comment]
Hi,
Done! 2.0.0 is out
https://github.com/etaque/elm-form/releases/tag/2.0.0

**Comment by sabine** [comment]
Thanks!
