### ISSUE TITLE
Allow other types than String for field keys

### ISSUE THREAD

**Issue by felixLam** [etaque/elm-form#83]
From what I can tell right now `Field` can only be used with type `String` for the keys. I would suggest that we extend this to use any comparable type (with convenience declarations falling back to string if that turns out to be needed). This would have the benefit that one can use union types. 

Right now with strings, one has to declare  "constants" for the keys or risk typos when referencing a field by key. With union types for keys the risk of typos would be somewhat lower and one could always be sure to at least reference a "legal" key for a given form.

In the example code the improvement would be that `"baz"` and `"bar"` could be replaced with typed field keys `ExampleFieldBaz` and `ExampleFieldBar`.

If you think that this is worthwhile I could give it a go.

**Comment by etaque** [comment]
Hi, that looks like a good idea! String keys are a weakness of elm-form, so yeah, let's try this :)

**Comment by felixLam** [comment]
Hi @etaque,

I started looking into this. It turns out that the string nature is deeply embedded into the logic as many places expect a dot separated path to a field. This would need to be refactored to use a list of the key type. Let's see if I can make any progress here.

Kind regards,

Felix

**Comment by felixLam** [comment]
Hi @etaque,

I think I got in over my head. The main issue I am facing is that I don't fully understand why there is a tree structure. My understanding is that this is to support groups of fields and to highlight validation errors at a group level. Is that correct?

I tried to push `List comparable` through the code base as the type for a key path, but got the compiler failing on me. 

I am not sure how important the field group are. But one idea might be that this can be done via a tagged union type. That would also do away with paths. My understanding would also be that key paths do not lend themselves to be strictly typed. In that world the following type would describe all fields:

```elm
-- A group of fields
type CredentialsFields = UserName | Email | Password

-- All possible fields in my form
type MyForm = Credentials CredentialsFields | Bar | Baz

type alias Model =
    { form : Form MyForm () OutputModel }

validation : Validation () OutputModel
validation =
    map5 OutputModel
        (field (CredentialsFields Email) email)
        (field (CredentialsFields UserName) string)
        (field (CredentialsFields Password) string)
        (field Bar string)
        (field Baz bool)
```

**Comment by cdevienne** [comment]
Hi @felixLam 

Your idea of using tagged union types looks promising, I think I will give it a try.

That said, unless I missed something huge, union types are not comparable, so we would have to use some custom type (probably a List(T, value) instead of a Dict for groups.

**Comment by etaque** [comment]
Yeah that's a promising thing, given that the main weakness of this lib is the use of strings for field names. But there is a lot of code here now, so it might be a better approach to start from scratch. Closing this issue, but thanks for you research @felixLam!

**Comment by qwfy** [comment]
I'm currently using a slightly safer, but dirty, way to handle the string key problem, namely, you define a sum type, `FieldName`, as your key, and call a `fieldNameToString` function every time you need to pass a string key to the library, at least, it prevents typo.

**Comment by felixLam** [comment]
That is what we have been doing as well.

**Comment by etaque** [comment]
How do you deal with field groups & lists then?

**Comment by felixLam** [comment]
We don't have those at the moment
