### ISSUE TITLE
Why use Html.Attributes.defaultValue over Html.Attributes.value?

### ISSUE THREAD

**Issue by YetAnotherMinion** [etaque/elm-form#89]
Use of `defaultValue` attribute for the `<input>` element breaks the Reset capability.

Is the goal to cache the view function for the form with Html.Lazy and not rerender the form at all even as the user inputs things? For my use case that is not the best trade-off to make because I would like to use the reset button on the form to clear the user inputs and put the form back into its default state.

When I change the two instances of `defaultValue` in `Form.Input` module to `value` I get the behavior I expect and cursory inspection it does not seem slow.

**Comment by ocharles** [comment]
Another oddity here is that if you dynamically change the "shape" of a form, surprising things can happen.

For example, take:

```elm
div [] <| List.concat [ if errors then errorsUl else [ ], [ textInput, passwordInput ] ]
```

In this case, if `errors` is `True`, then we show a `<ul>` of errors. On page load, assume `errors` is False, so errors are not displayed. On submission, `errors` may become `True`. This means that (in VirtualDom), the text `input` becomes a `<ul>`, the password input becomes a text input, and we need to add a new `input` to the end. But we can't reset the value of the password input, so what actually ends up happening is the result of the password field is now revealed to anyone looking at the screen! I can make a full example if this is unclear.

**Comment by pablohirafuji** [comment]
This issue has been discussed before. Please read issues #65 and #54. The main reason is that setting the `value` attribute has hard side effect on Test frameworks, while `defaultValue` has practically no side effect. The user can always set the `value` attribute, but not unset.

If you want to use the `value` attribute, the doc has an example: https://github.com/etaque/elm-form#initial-values-and-reset

**Comment by etaque** [comment]
That behaviour will be better documenter in the future, thanks @pablohirafuji for watching these issues.

@ocharles yes please, you can open a new issue for this, however it looks like a virtual dom bug to me!
