### ISSUE TITLE
Avoid getChangedFields returning fields if you type something and then delete it to initial state

### ISSUE THREAD

**Issue by janjelinek** [etaque/elm-form#94]
Hi there,

what do you think about checking default value when is triggered `Input`and removing fields from `changedFields` in `Model` when it becomes unchanged again. 

I mean situation when someone types some text to input and then delete it.

Reason is when you want to show active submit button only if some field is changed you need somehow get info about this change and `changedFields` seems to be ideal but not in current state.

If you agree with this solution I should prepare PR with change if it's necessary.

**Comment by etaque** [comment]
Hi,
Yes, that make sense. PR welcome!
