### ISSUE TITLE
Url validator is far too restrictive

### ISSUE THREAD

**Issue by ocharles** [etaque/elm-form#96]
For example, `_` isn't allowed. I'd suggest removing this validator entirely, unless one can be provided that doesn't reject *any* valid URLs.

**Comment by etaque** [comment]
Agree, this is a bad regexp, let's remove it.

**Comment by etaque** [comment]
If we follow the same logic, email regexp should be remove. Thoughts?
I think this is useful for users, shall we:
 - create a contrib lib with a bag of useful validators (url, email.. what more?)
 - or improve those two validators, cost being having some terrific regexps in lib source 😨

**Comment by ocharles** [comment]
Does the email regular expression reject valid email addresses? If so, then yes. I generally just go with a very permissive check on email addresses: anything@anything.anything :smile: .

WRT email, prior art is https://metacpan.org/pod/Email::Valid and https://hackage.haskell.org/package/email-validate. Maybe there is something on NPM that can be used with a native import, don't really see the point of writing yet another validator just with the benefit of being written in Elm.

**Comment by etaque** [comment]
I think the email regexp is quite solid, it's the one used in Play Framework for a long time now. So, I'm probably just gonna remove the url validation in the next (major) version.
